<!-- Do not edit this file - it is a template. Please edit the index.ts file in /static/3d_printed_member -->
<script setup>
import Accordion from '../../vue/accordion/Accordion.vue'
import { faq } from '../../static/faq'
</script>
<template>
    <div>
        <Accordion v-for="member in faq.faq" class="mb-4">
            <template v-slot:title>
                <span class="font-semibold text-xl">{{ member.question }}</span>
            </template>
            <template v-slot:content>
                <div>
                    <span class="">
                        <blockquote>
                            <ul style="list-style: none;">
                                <li>{{ member.answer }}</li>
                                <p v-if="member.hyper_link != NULL && member.hyper_link != ''">
                                    <a :href="member.hyper_link" target="_blank">{{ member.link_description }}</a>
                                </p>
                            </ul>
                        </blockquote>
                    </span>
                </div>
            </template>
        </Accordion>
    </div>
</template>