<!-- Do not edit this file - it is a template. Please edit the index.ts file in /static/3d_printed_parts -->
<script setup>
import Accordion from '../../vue/accordion/Accordion.vue'
import { printed_parts } from '../../static/3d_printed_parts'
</script>
<template>
    <div>
        <Accordion v-for="parts in printed_parts.hmds" class="mb-4">
            <template v-slot:title>
                <span class="font-semibold text-xl">{{ parts.hmd }}</span>
            </template>
            <template v-slot:content>
                <div>
                    <span class="">
                        <blockquote>
                            <ul style="list-style: none;">
                                <p v-if="parts.hyper_links != NULL && parts.hyper_links != ''"
                                    v-for="hyper_link in parts.hyper_links">
                                    <a :href="hyper_link.url" target="_blank">{{ hyper_link.desc }}</a>
                                </p>
                                <li v-for="part in parts.parts" :key="part">{{ part }}</li>
                            </ul>
                        </blockquote>
                    </span>
                </div>
            </template>
        </Accordion>
    </div>
</template>